#cloud-config
apt_update: true
packages:
  - openvpn
  - easy-rsa
  - curl
runcmd:
  - IPADDR=$(curl -s http://169.254.169.254/metadata/v1/interfaces/public/0/ipv4/address)
  - gunzip -c /usr/share/doc/openvpn/examples/sample-config-files/server.conf.gz > /etc/openvpn/server.conf
  - sed -i -e 's/dh dh1024.pem/dh dh2048.pem/' /etc/openvpn/server.conf
  - sed -i -e 's/;push "redirect-gateway def1 bypass-dhcp"/push "redirect-gateway def1 bypass-dhcp"/' /etc/openvpn/server.conf
  - sed -i -e 's/;push "dhcp-option DNS 208.67.222.222"/push "dhcp-option DNS 208.67.222.222"/' /etc/openvpn/server.conf
  - sed -i -e 's/;push "dhcp-option DNS 208.67.220.220"/push "dhcp-option DNS 208.67.220.220"/' /etc/openvpn/server.conf
  - sed -i -e 's/;user nobody/user nobody/' /etc/openvpn/server.conf
  - sed -i -e 's/;tls-auth ta.key 0/tls-auth ta.key 0/' /etc/openvpn/server.conf
  - sed -i -e 's/;group nogroup/group nogroup/' /etc/openvpn/server.conf
  - echo 1 > /proc/sys/net/ipv4/ip_forward
  - sed -i -e 's/#net.ipv4.ip_forward=1/net.ipv4.ip_forward=1/' /etc/sysctl.conf
  - ufw allow ssh
  - ufw allow 1194/udp
  - sed -i -e 's/DEFAULT_FORWARD_POLICY="DROP"/DEFAULT_FORWARD_POLICY="ACCEPT"/' /etc/default/ufw
  - sed -i "1i# START OPENVPN RULES\n# NAT table rules\n*nat\n:POSTROUTING ACCEPT [0:0]\n# Allow traffic from OpenVPN client to eth0\n\n-A POSTROUTING -s 10.8.0.0/8 -o eth0 -j MASQUERADE\nCOMMIT\n# END OPENVPN RULES\n" /etc/ufw/before.rules
  - ufw --force enable

  - cp -r /usr/share/easy-rsa/ /etc/openvpn
  - mkdir /etc/openvpn/easy-rsa/keys
  - sed -i -e 's/KEY_NAME="EasyRSA"/KEY_NAME="server"/' /etc/openvpn/easy-rsa/vars
  - openssl dhparam -out /etc/openvpn/dh2048.pem 2048
  - cd /etc/openvpn/easy-rsa && . ./vars
  # Optionally set indentity information for certificates:
  # - export KEY_COUNTRY="<%COUNTRY%>" # 2-char country code
  # - export KEY_PROVINCE="<%PROVINCE%>" # 2-char state/province code
  # - export KEY_CITY="<%CITY%>" # City name
  # - export KEY_ORG="<%ORG%>" # Org/company name
  # - export KEY_EMAIL="<%EMAIL%>" # Email address
  # - export KEY_OU="<%ORG_UNIT%>" # Orgizational unit / department
  - cd /etc/openvpn/easy-rsa && ./clean-all
  - cd /etc/openvpn/easy-rsa && ./build-ca --batch
  - cd /etc/openvpn/easy-rsa && ./build-key-server --batch server
  - cd /etc/openvpn/easy-rsa/keys && openvpn --genkey --secret ta.key
  - cp /etc/openvpn/easy-rsa/keys/server.crt /etc/openvpn
  - cp /etc/openvpn/easy-rsa/keys/server.key /etc/openvpn
  - cp /etc/openvpn/easy-rsa/keys/ca.crt /etc/openvpn
  - cp /etc/openvpn/easy-rsa/keys/ta.key /etc/openvpn
  - service openvpn start

  - cd /etc/openvpn/easy-rsa && ./build-key --batch shas_client1
  - cd /etc/openvpn/easy-rsa && ./build-key --batch shas_client2
  - cd /etc/openvpn/easy-rsa && ./build-key --batch shas_client3
  - cd /etc/openvpn/easy-rsa && ./build-key --batch shas_client4
  - cd /etc/openvpn/easy-rsa && ./build-key --batch shas_client5
  - cd /etc/openvpn/easy-rsa && ./build-key --batch shas_client6
  - cd /etc/openvpn/easy-rsa && ./build-key --batch shas_client7
  - cd /etc/openvpn/easy-rsa && ./build-key --batch shas_client8
  - cd /etc/openvpn/easy-rsa && ./build-key --batch shas_client9
  - cd /etc/openvpn/easy-rsa && ./build-key --batch shas_client10

  - cp /usr/share/doc/openvpn/examples/sample-config-files/client.conf /etc/openvpn/easy-rsa/keys/client.ovpn
  - sed -i -e "s/my-server-1/$IPADDR/" /etc/openvpn/easy-rsa/keys/client.ovpn
  - sed -i -e 's/;user nobody/user nobody/' /etc/openvpn/easy-rsa/keys/client.ovpn
  - sed -i -e 's/;tls-auth ta.key 1/tls-auth ta.key 1/' /etc/openvpn/easy-rsa/keys/client.ovpn
  - sed -i -e 's/;group nogroup/group nogroup/' /etc/openvpn/easy-rsa/keys/client.ovpn
  - sed -i -e 's/ca ca.crt//' /etc/openvpn/easy-rsa/keys/client.ovpn
  - sed -i -e 's/cert client.crt//' /etc/openvpn/easy-rsa/keys/client.ovpn
  - sed -i -e 's/key client.key//' /etc/openvpn/easy-rsa/keys/client.ovpn
  - echo "<ca>" >> /etc/openvpn/easy-rsa/keys/client.ovpn
  - cat /etc/openvpn/ca.crt >> /etc/openvpn/easy-rsa/keys/client.ovpn
  - echo "</ca>" >> /etc/openvpn/easy-rsa/keys/client.ovpn
  - echo "<cert>" >> /etc/openvpn/easy-rsa/keys/client.ovpn

  - cp /etc/openvpn/easy-rsa/keys/client.ovpn /etc/openvpn/easy-rsa/keys/client2.ovpn
  - cp /etc/openvpn/easy-rsa/keys/client.ovpn /etc/openvpn/easy-rsa/keys/client3.ovpn
  - cp /etc/openvpn/easy-rsa/keys/client.ovpn /etc/openvpn/easy-rsa/keys/client4.ovpn
  - cp /etc/openvpn/easy-rsa/keys/client.ovpn /etc/openvpn/easy-rsa/keys/client5.ovpn
  - cp /etc/openvpn/easy-rsa/keys/client.ovpn /etc/openvpn/easy-rsa/keys/client6.ovpn
  - cp /etc/openvpn/easy-rsa/keys/client.ovpn /etc/openvpn/easy-rsa/keys/client7.ovpn
  - cp /etc/openvpn/easy-rsa/keys/client.ovpn /etc/openvpn/easy-rsa/keys/client8.ovpn
  - cp /etc/openvpn/easy-rsa/keys/client.ovpn /etc/openvpn/easy-rsa/keys/client9.ovpn
  - cp /etc/openvpn/easy-rsa/keys/client.ovpn /etc/openvpn/easy-rsa/keys/client10.ovpn

  # shas_client1
  - openssl x509 -outform PEM -in /etc/openvpn/easy-rsa/keys/shas_client1.crt >> /etc/openvpn/easy-rsa/keys/client.ovpn
  - echo "</cert>" >> /etc/openvpn/easy-rsa/keys/client.ovpn
  - echo "<key>" >> /etc/openvpn/easy-rsa/keys/client.ovpn
  - cat /etc/openvpn/easy-rsa/keys/shas_client1.key >> /etc/openvpn/easy-rsa/keys/client.ovpn
  - echo "</key>" >> /etc/openvpn/easy-rsa/keys/client.ovpn
  # shas_client2
  - openssl x509 -outform PEM -in /etc/openvpn/easy-rsa/keys/shas_client2.crt >> /etc/openvpn/easy-rsa/keys/client2.ovpn
  - echo "</cert>" >> /etc/openvpn/easy-rsa/keys/client2.ovpn
  - echo "<key>" >> /etc/openvpn/easy-rsa/keys/client2.ovpn
  - cat /etc/openvpn/easy-rsa/keys/shas_client2.key >> /etc/openvpn/easy-rsa/keys/client2.ovpn
  - echo "</key>" >> /etc/openvpn/easy-rsa/keys/client2.ovpn
  # shas_client3
  - openssl x509 -outform PEM -in /etc/openvpn/easy-rsa/keys/shas_client3.crt >> /etc/openvpn/easy-rsa/keys/client3.ovpn
  - echo "</cert>" >> /etc/openvpn/easy-rsa/keys/client3.ovpn
  - echo "<key>" >> /etc/openvpn/easy-rsa/keys/client3.ovpn
  - cat /etc/openvpn/easy-rsa/keys/shas_client3.key >> /etc/openvpn/easy-rsa/keys/client3.ovpn
  - echo "</key>" >> /etc/openvpn/easy-rsa/keys/client3.ovpn
  # shas_client4
  - openssl x509 -outform PEM -in /etc/openvpn/easy-rsa/keys/shas_client4.crt >> /etc/openvpn/easy-rsa/keys/client4.ovpn
  - echo "</cert>" >> /etc/openvpn/easy-rsa/keys/client4.ovpn
  - echo "<key>" >> /etc/openvpn/easy-rsa/keys/client4.ovpn
  - cat /etc/openvpn/easy-rsa/keys/shas_client4.key >> /etc/openvpn/easy-rsa/keys/client4.ovpn
  - echo "</key>" >> /etc/openvpn/easy-rsa/keys/client4.ovpn
  # shas_client5
  - openssl x509 -outform PEM -in /etc/openvpn/easy-rsa/keys/shas_client5.crt >> /etc/openvpn/easy-rsa/keys/client5.ovpn
  - echo "</cert>" >> /etc/openvpn/easy-rsa/keys/client5.ovpn
  - echo "<key>" >> /etc/openvpn/easy-rsa/keys/client5.ovpn
  - cat /etc/openvpn/easy-rsa/keys/shas_client5.key >> /etc/openvpn/easy-rsa/keys/client5.ovpn
  - echo "</key>" >> /etc/openvpn/easy-rsa/keys/client5.ovpn
  # shas_client6
  - openssl x509 -outform PEM -in /etc/openvpn/easy-rsa/keys/shas_client6.crt >> /etc/openvpn/easy-rsa/keys/client6.ovpn
  - echo "</cert>" >> /etc/openvpn/easy-rsa/keys/client6.ovpn
  - echo "<key>" >> /etc/openvpn/easy-rsa/keys/client6.ovpn
  - cat /etc/openvpn/easy-rsa/keys/shas_client6.key >> /etc/openvpn/easy-rsa/keys/client6.ovpn
  - echo "</key>" >> /etc/openvpn/easy-rsa/keys/client6.ovpn
  # shas_client7
  - openssl x509 -outform PEM -in /etc/openvpn/easy-rsa/keys/shas_client7.crt >> /etc/openvpn/easy-rsa/keys/client7.ovpn
  - echo "</cert>" >> /etc/openvpn/easy-rsa/keys/client7.ovpn
  - echo "<key>" >> /etc/openvpn/easy-rsa/keys/client7.ovpn
  - cat /etc/openvpn/easy-rsa/keys/shas_client7.key >> /etc/openvpn/easy-rsa/keys/client7.ovpn
  - echo "</key>" >> /etc/openvpn/easy-rsa/keys/client7.ovpn
  # shas_client8
  - openssl x509 -outform PEM -in /etc/openvpn/easy-rsa/keys/shas_client8.crt >> /etc/openvpn/easy-rsa/keys/client8.ovpn
  - echo "</cert>" >> /etc/openvpn/easy-rsa/keys/client8.ovpn
  - echo "<key>" >> /etc/openvpn/easy-rsa/keys/client8.ovpn
  - cat /etc/openvpn/easy-rsa/keys/shas_client8.key >> /etc/openvpn/easy-rsa/keys/client8.ovpn
  - echo "</key>" >> /etc/openvpn/easy-rsa/keys/client8.ovpn
  # shas_client9
  - openssl x509 -outform PEM -in /etc/openvpn/easy-rsa/keys/shas_client9.crt >> /etc/openvpn/easy-rsa/keys/client9.ovpn
  - echo "</cert>" >> /etc/openvpn/easy-rsa/keys/client9.ovpn
  - echo "<key>" >> /etc/openvpn/easy-rsa/keys/client9.ovpn
  - cat /etc/openvpn/easy-rsa/keys/shas_client9.key >> /etc/openvpn/easy-rsa/keys/client9.ovpn
  - echo "</key>" >> /etc/openvpn/easy-rsa/keys/client9.ovpn
  # shas_client10
  - openssl x509 -outform PEM -in /etc/openvpn/easy-rsa/keys/shas_client10.crt >> /etc/openvpn/easy-rsa/keys/client10.ovpn
  - echo "</cert>" >> /etc/openvpn/easy-rsa/keys/client10.ovpn
  - echo "<key>" >> /etc/openvpn/easy-rsa/keys/client10.ovpn
  - cat /etc/openvpn/easy-rsa/keys/shas_client10.key >> /etc/openvpn/easy-rsa/keys/client10.ovpn
  - echo "</key>" >> /etc/openvpn/easy-rsa/keys/client10.ovpn

  - mkdir /root/openvpn/  
  - mkdir /root/openvpn/client1
  - mkdir /root/openvpn/client2
  - mkdir /root/openvpn/client3
  - mkdir /root/openvpn/client4
  - mkdir /root/openvpn/client5
  - mkdir /root/openvpn/client6
  - mkdir /root/openvpn/client7
  - mkdir /root/openvpn/client8
  - mkdir /root/openvpn/client9
  - mkdir /root/openvpn/client10

  - cp /etc/openvpn/easy-rsa/keys/client.ovpn /root/openvpn/client1
  - cp /etc/openvpn/easy-rsa/keys/shas_client1.crt /root/openvpn/client1
  - cp /etc/openvpn/easy-rsa/keys/shas_client1.key /root/openvpn/client1
  - cp /etc/openvpn/easy-rsa/keys/ca.crt /root/openvpn/client1
  - cp /etc/openvpn/ta.key /root/openvpn/client1

  - cp /etc/openvpn/easy-rsa/keys/client2.ovpn /root/openvpn/client2
  - cp /etc/openvpn/easy-rsa/keys/shas_client2.crt /root/openvpn/client2
  - cp /etc/openvpn/easy-rsa/keys/shas_client2.key /root/openvpn/client2
  - cp /etc/openvpn/easy-rsa/keys/ca.crt /root/openvpn/client2
  - cp /etc/openvpn/ta.key /root/openvpn/client2

  - cp /etc/openvpn/easy-rsa/keys/client3.ovpn /root/openvpn/client3
  - cp /etc/openvpn/easy-rsa/keys/shas_client3.crt /root/openvpn/client3
  - cp /etc/openvpn/easy-rsa/keys/shas_client3.key /root/openvpn/client3
  - cp /etc/openvpn/easy-rsa/keys/ca.crt /root/openvpn/client3
  - cp /etc/openvpn/ta.key /root/openvpn/client3

  - cp /etc/openvpn/easy-rsa/keys/client4.ovpn /root/openvpn/client4
  - cp /etc/openvpn/easy-rsa/keys/shas_client4.crt /root/openvpn/client4
  - cp /etc/openvpn/easy-rsa/keys/shas_client4.key /root/openvpn/client4
  - cp /etc/openvpn/easy-rsa/keys/ca.crt /root/openvpn/client4
  - cp /etc/openvpn/ta.key /root/openvpn/client4

  - cp /etc/openvpn/easy-rsa/keys/client5.ovpn /root/openvpn/client5
  - cp /etc/openvpn/easy-rsa/keys/shas_client5.crt /root/openvpn/client5
  - cp /etc/openvpn/easy-rsa/keys/shas_client5.key /root/openvpn/client5
  - cp /etc/openvpn/easy-rsa/keys/ca.crt /root/openvpn/client5
  - cp /etc/openvpn/ta.key /root/openvpn/client5

  - cp /etc/openvpn/easy-rsa/keys/client6.ovpn /root/openvpn/client6
  - cp /etc/openvpn/easy-rsa/keys/shas_client6.crt /root/openvpn/client6
  - cp /etc/openvpn/easy-rsa/keys/shas_client6.key /root/openvpn/client6
  - cp /etc/openvpn/easy-rsa/keys/ca.crt /root/openvpn/client6
  - cp /etc/openvpn/ta.key /root/openvpn/client6

  - cp /etc/openvpn/easy-rsa/keys/client7.ovpn /root/openvpn/client7
  - cp /etc/openvpn/easy-rsa/keys/shas_client7.crt /root/openvpn/client7
  - cp /etc/openvpn/easy-rsa/keys/shas_client7.key /root/openvpn/client7
  - cp /etc/openvpn/easy-rsa/keys/ca.crt /root/openvpn/client1
  - cp /etc/openvpn/ta.key /root/openvpn/client7

  - cp /etc/openvpn/easy-rsa/keys/client8.ovpn /root/openvpn/client8
  - cp /etc/openvpn/easy-rsa/keys/shas_client8.crt /root/openvpn/client8
  - cp /etc/openvpn/easy-rsa/keys/shas_client8.key /root/openvpn/client8
  - cp /etc/openvpn/easy-rsa/keys/ca.crt /root/openvpn/client8
  - cp /etc/openvpn/ta.key /root/openvpn/client8

  - cp /etc/openvpn/easy-rsa/keys/client9.ovpn /root/openvpn/client9
  - cp /etc/openvpn/easy-rsa/keys/shas_client9.crt /root/openvpn/client9
  - cp /etc/openvpn/easy-rsa/keys/shas_client9.key /root/openvpn/client9
  - cp /etc/openvpn/easy-rsa/keys/ca.crt /root/openvpn/client9
  - cp /etc/openvpn/ta.key /root/openvpn/client9

  - cp /etc/openvpn/easy-rsa/keys/client10.ovpn /root/openvpn/client10
  - cp /etc/openvpn/easy-rsa/keys/shas_client10.crt /root/openvpn/client10
  - cp /etc/openvpn/easy-rsa/keys/shas_client10.key /root/openvpn/client10
  - cp /etc/openvpn/easy-rsa/keys/ca.crt /root/openvpn/client10
  - cp /etc/openvpn/ta.key /root/openvpn/client10

